### PR TITLE
Test with Ruby 3.0

### PR DESCRIPTION
**Pull request by n-rodriguez**
## Description
Detail your changes here.  
A few sentences describing the overall goals of the pull request's commits will suffice.
Some questions you might answer:

* Why was this change required?
* Did you have any tough decisions to make? Which one(s) did you go with and why?
* Are there any deployment impacts to this change?
* Is there something you aren't happy with or that needs extra attention?

## Testing
Outline steps to test your changes.

1. Go here.
1. Click this.
1. See that.

## To-Dos
- [ ] tests
- [ ] documentation

## References
* [GitHub Issue ####](https://github.com/drapergem/draper/issues/####)
* [GitHub Pull Request ####](https://github.com/drapergem/draper/pull/####)

### CODE REVIEW

**Comment by codebycliff** [comment]
How do we want to go about this? Do we want to merge this in first, and then merge the [kwargs PR](https://github.com/drapergem/draper/pull/885) into draper master afterward?

**Comment by n-rodriguez** [comment]
> How do we want to go about this? Do we want to merge this in first, and then merge the kwargs PR into draper master afterward?

Sounds good 👍

**Comment by codebycliff** [comment]
@oieioi Do you want to approve this and merge it into your branch when you get a chance?

**Review by oieioi — APPROVED** [review]
Thanks!

**Pull request merged**
